import bcrypt from 'bcryptjs';

const data = {
  books: [
    {
      //_id: '1',
      image: '/img/metro2033.png',
      title: 'Metro 2033',
      author: 'Dmitry Glukhovsky',
      release: 2011,
      page: 439,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-2033',
      stock: 3,
    },
    {
      //_id: '2',
      image: '/img/metro2034.png',
      title: 'Metro 2034',
      author: 'Dmitry Glukhovsky',
      release: 2011,
      page: 271,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-2034',
      stock: 0,
    },
    {
      //_id: '3',
      image: '/img/metro2035.png',
      title: 'Metro 2035',
      author: 'Dmitry Glukhovsky',
      release: 2017,
      page: 482,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-2035',
      stock: 3,
    },
    {
      //_id: '4',
      image: '/img/metroazeg.png',
      title: 'Az ég gyökerei',
      author: 'Tullio Avoledo',
      release: 2014,
      page: 570,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-azeg',
      stock: 3,
    },
    {
      //_id: '5',
      image: '/img/metroafeny.png',
      title: 'A fény felé',
      author: 'Andrej Gyjakov',
      release: 2014,
      page: 296,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-afeny',
      stock: 3,
    },
    {
      //_id: '6',
      image: '/img/metrovissza.png',
      title: 'Vissza a sötétségbe',
      author: 'Dmitry Glukhovsky',
      release: 2014,
      page: 332,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-vissza',
      stock: 3,
    },
    {
      //_id: '7',
      image: '/img/metroapetervari.png',
      title: 'A pétervári háború',
      author: 'Simun Vrocsek',
      release: 2015,
      page: 596,
      category: 'Metro series',
      price: 10,
      description: 'Poszt apokaliptikus világ',
      key: 'metro-apetervari',
      stock: 3,
    },
  ],
  users: [
    {
      name: 'Benjámin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('admin1'),
      admin: true,
    },
    {
      name: 'User1',
      email: 'user@example.com',
      password: bcrypt.hashSync('user1'),
      admin: false,
    },
  ],
};

export default data;
